name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Use Node.js 14.6.0
        uses: actions/setup-node@v1
        with:
          node-version: '14.6.0'

      - name: Install npm packages
        run: |
          npm i
        env:
          CI: true

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          target: runner
          file: Dockerfile-prod
          context: .
          push: true
          tags: provenanceio/explorer-frontend:latest
  build-local:
    env:
      REACT_APP_DOCKER_ENV: local
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Use Node.js 14.6.0
        uses: actions/setup-node@v1
        with:
          node-version: '14.6.0'

      - name: Install npm packages
        run: |
          npm i
        env:
          CI: true

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          target: runner
          file: Dockerfile-prod
          context: .
          push: true
          tags: provenanceio/explorer-frontend:local